[WIP][Intermediate Representation] Translate analyzer IR to analysis
sql-machine-learning/sqlflow pull request #1041
Opened 2019-10-20 15:38 UTC by weiguoz

fix #975

2019-10-21 20:41 UTC, tonyyang-svail requested changes
Please move `pkg/sql/codegen/analyzer/*.go` to `pkg/sql/codegen/xgboost/`.

It is important to keep the following mapping consistent.

1. TrainIR => xgboost.Train
1. PredictIR => xgboost.Predict
1. AnalyzeIR => xgboost.Analyze

And we can generate the documentation for train/pred/analyze XGBoost all together.

2019-10-21 20:41 UTC, tonyyang-svail commented on pkg/sql/codegen/analyzer/codegen.go
> +		return "", fmt.Errorf("unsupported explainer")
=> `fmt.Errorf("unsupported explainer %s", ir.Explainer)`

2019-10-21 20:41 UTC, tonyyang-svail commented on pkg/sql/codegen/analyzer/codegen.go
> +	return "", fmt.Errorf("unsupported model:%s", ir.TrainIR.Estimator)
`model:%s` => `model: %s`

2019-10-21 20:41 UTC, tonyyang-svail commented on pkg/sql/codegen/analyzer/codegen.go
> +	shapSummaryAttributes = "shap_summary"
Please switch to `attribute.Dictionary` in the upcoming PRs. Example:

https://github.com/sql-machine-learning/sqlflow/blob/eb19db58b36640b58cca0e6b979be0dff7101e4a/pkg/sql/codegen/xgboost/codegen.go#L37-L47

2019-10-21 20:41 UTC, tonyyang-svail commented on pkg/sql/codegen/analyzer/codegen.go
> +func GenAnalysis(ir *codegen.AnalyzeIR, modelPath string) (string, error) {
GenAnalysis => Analyze. This function should be called as `xgboost.Analyze`.

2019-10-22 14:10 UTC, typhoonzero reviewed
@tonyyang-svail @weiguoz  should we put this codegen under directory `codegen/shap` because it's generating SHAP code, just like `codegen/tensorflow`?

2019-10-22 14:10 UTC, typhoonzero commented on pkg/sql/codegen/xgboost/codegen_analyze.go
> +func resolveParames(attrs map[string]interface{}, group string) (map[string]interface{}, error) {
resolveParames -> resolveParams

2019-10-22 15:00 UTC, weiguoz commented
> @tonyyang-svail @weiguoz should we put this codegen under directory `codegen/shap` because it's generating SHAP code, just like `codegen/tensorflow`?

It looks intuitive to split directories by dependency packages. However, from the perspective of the model lifecycle, the current implementation is also reasonable. Plus, more code for the `PREDICT` process in codegen would be shared with the `analyze` process.

2019-10-22 16:59 UTC, tonyyang-svail commented
> @tonyyang-svail @weiguoz should we put this codegen under directory codegen/shap because it's generating SHAP code, just like codegen/tensorflow?

@typhoonzero We train/predict/analyze an XGBoost model, their documentation should be together, so the generation of analyzing code should in `xgboost` package.

2019-10-22 17:00 UTC, tonyyang-svail approved these changes
LGTM.

2019-10-23 00:22 UTC, typhoonzero approved these changes
LGTM++

2019-10-23 01:12 UTC, merged