Add quickstart in Chinese
sql-machine-learning/sqlflow pull request #2124
Opened 2020-04-19 13:01 UTC by Yancey1989

related issue #2090

2020-04-20 14:58 UTC, lhw362950217 requested changes

2020-04-20 14:58 UTC, lhw362950217 commented on doc/usage/quickstart.cn.md
> +我们以[波士顿房价](https://www.kaggle.com/c/boston-housing)数据集为例，演示如何笔记本上电脑上的 Jupyter Notebook 中使用 SQLFlow 训练模型，并用训练好的模型进行预测，最后分析每个特征对模型的贡献。
如何笔记本上电脑上 -> 如何在笔记本电脑上

2020-04-20 14:58 UTC, lhw362950217 commented on doc/usage/quickstart.cn.md
> +1. 在笔记本上[安装 Docker]}(https://docs.docker.com/get-docker/)
多余的 }

2020-04-20 14:58 UTC, lhw362950217 commented on doc/usage/quickstart.cn.md
> +1. 启动 SQLFlow： `docker run -it -p 8888:8888 sqlflow/sqlflow`
是不是要说一下下载哪个镜像？

2020-04-20 14:58 UTC, lhw362950217 commented on doc/usage/quickstart.cn.md
> +1. 在 Notebook 中创建 Python3 Kernel
建议修改下序号吧，现在全是1

2020-04-20 16:15 UTC, shendiaomo commented on doc/usage/quickstart.cn.md
> +1. 在 Notebook 中创建 Python3 Kernel
这个应该是markdown的语法，展现时是会自动替换的

2020-04-20 17:49 UTC, wangkuiyi commented on doc/usage/quickstart.cn.md
> +1. 在 Notebook 中创建 Python3 Kernel
我感觉这里的问题是不要用 bullet。用 `###` 视觉效果会更好。

2020-04-20 17:49 UTC, wangkuiyi commented on doc/usage/quickstart.cn.md
> +1. 在 Notebook 中创建 Python3 Kernel
"在 Notebook 中创建 Python 3 kernel " => "创建一个 Notebook，选择 Python 3 kernel"

2020-04-20 17:49 UTC, wangkuiyi commented on doc/usage/quickstart.cn.md
> +    ![](/doc/usage/figures/quickstart_train.jpg)
其他两幅图里都既展示了 Jupyter Notebook 里的 SQL 语句也展示了执行结果。这里貌似只有执行结果。要不要重新抓一下图？

2020-04-20 17:49 UTC, wangkuiyi commented on doc/usage/quickstart.cn.md
> +![](/doc/usage/figures/py3_kernel.jpg)
这幅图的左右边缘太宽了，所以文字太小了，和下面的图相比视觉效果不一致。导致这篇文档排版出来之后不美观，也看不清。把这个图修一下，两边边缘去掉吧。

2020-04-21 18:41 UTC, wangkuiyi commented on doc/usage/quickstart.cn.md
> +我们以[波士顿房价](https://www.kaggle.com/c/boston-housing)数据集为例，演示如何笔记本上电脑上的 Jupyter Notebook 中使用 SQLFlow 训练模型，并用训练好的模型进行预测，最后分析每个特征对模型的贡献。
Fixed

2020-04-21 18:50 UTC, wangkuiyi submitted a review, later dismissed

2020-04-22 01:04 UTC, lhw362950217 commented on doc/usage/quickstart.cn.md
> +我们以[波士顿房价](https://www.kaggle.com/c/boston-housing)数据集为例，演示如何在笔记本上电脑上的 Jupyter Notebook 中使用 SQLFlow 训练模型，并用训练好的模型进行预测，最后分析每个特征对模型的贡献。
笔记本上电脑上 -> 笔记本电脑上, 多了个’上‘

2020-04-22 03:40 UTC, lhw362950217 approved these changes
LGTM

2020-04-22 06:16 UTC, merged