Support importing any custom model package
sql-machine-learning/sqlflow pull request #2204
Opened 2020-05-09 07:37 UTC by typhoonzero

Fix https://github.com/sql-machine-learning/sqlflow/issues/2162

2020-05-09 08:04 UTC, Yancey1989 commented on pkg/sql/codegen/tensorflow/template_train.go
> +model_import_name = sqlflow_submitter.get_import_name("""{{.Estimator}}""")
Move to Python code can keep the template cleaner?

2020-05-11 03:30 UTC, wangkuiyi commented on pkg/sql/pai_submitter.go
> +	fmt.Printf("submitting with model dep: %s\n", estimator)
dep => definition

2020-05-11 03:30 UTC, wangkuiyi commented on pkg/sql/codegen/pai/template_tf.go
> +    print("failed to import %s: %s" % (model_import_name, e))
This segment of code appears 5 times in this PR.  It seems should be defined as a function

```python
def sqlflow_submitter.import_model_def(estimator_cls_name):
    model_import_name = sqlflow_submitter.get_import_name(estimator_cls_name)
    try:
        globals()[model_import_name] = __import__(model_import_name)
    except Exception as e:
        print("failed to import %s: %s" % (model_import_name, e))
```

and we call it here as

```python
sqlflow_submitter.import_model_def("""{{.Estimator}}""")
```

2020-05-15 00:52 UTC, wangkuiyi approved these changes

2020-05-15 00:54 UTC, wangkuiyi requested changes
@typhoonzero This PR includes changes to .travis.yml, which reverted some of my recent changes. How about revert these changes to .travis.yml?

2020-05-15 17:42 UTC, wangkuiyi approved these changes

2020-05-16 03:15 UTC, merged